name: Build and Push Docker Image, Kubernetes deployment

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract version from file
      id: vars
      run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/sample:${{ env.VERSION }}
          ${{ secrets.DOCKER_USERNAME }}/sample:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Extract version from file
      id: vars
      run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

    - name: Replace version in Kubernetes deployment
      run: |
        sed -i "s/VERSION_PLACEHOLDER/${{ env.VERSION }}/g" k8s/deployment.yaml

    - name: Apply Kubernetes deployment
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml